development: &default
  adapter: postgresql
  encoding: utf8
  database: 
  host: localhost
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: utf8
  database:
  pool: 5
  username:
  password:

