development: &default
  adapter: postgresql
  database: annotation_studio_development
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: annotation_studio_test
