default:
  site_name: 'Public'
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  brand: 'shared/default_brand'
public:
  site_name: 'Public'
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
amherst:
  site_name: 'Amherst'
  site_color: '#2C0463'
andersen:
  site_name: 'Andersen'
  site_color: '#997F3D'
barnard:
  site_name: 'Barnard College'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Barnard College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#005596'
breck:
  site_name: 'Breck'
  site_color: '#000080'
bucknell:
  site_name: 'Bucknell University'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Bucknell University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#00337F'
demo:
  site_name: 'Demo'
  site_color: '#BDBDBD'
gatech:
  site_name: 'Georgia Tech'
  site_color: '#B3A369'
grinnell:
  site_name: 'Grinnell College'
  site_color: '#DA291C'
harvard:
  site_name: 'Harvard'
  site_color: '#A51C30'
humboldt:
  site_name: 'HU Berlin'
  site_color: '#010963'
merchant-of-venice:
  site_name: 'Merchant of Venice'
  site_color: '#D2B48C'
mit:
  site_name: 'MIT'
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#A31F34'
  brand: 'shared/default_brand'
newhaven:
  site_name: 'University of New Haven'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>University of New Haven</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFD700'
stonybrook:
  site_name: 'Stony Brook'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Stony Brook University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#990000'
uma:
  site_name: 'UMass Amherst'
  site_color: '#881c1c'
umb:
  site_name: 'UMass Boston'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>University of Massachusetts, Boston</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#38197A'
uw:
  site_name: 'University of Washington'
  site_color: '#B7A57A'
vassar:
  site_name: 'Vassar'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Vassar College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#800000'
washjeff:
  site_name: 'Washington and Jefferson'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Washington and Jefferson College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FF0000'
wellesley:
  site_name: 'Wellesley'
  site_color: '#002776'
wheatoncollege:
  site_name: 'Wheaton College'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Wheaton College</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFA5000'
wit:
  site_name: 'WIT'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Wentworth Institute of Technology</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#FFD700'
wlu:
  site_name: 'WLU'
  welcome_message: "Welcome to Annotation Studio Staging at <strong>Washington and Lee University</strong>"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#F169E1'
